#!/usr/bin/env bash

echo "RELATÓRIO DE DESLIGAMENTOS E REINICIALIZAÇÕES"
echo "Data do relatório: $(date +'%d/%m/%Y')"
echo "----------------------------------------"

last -x | grep -E 'shutdown|reboot' | while read linha
do
    data=$(echo "$linha" | awk '{print $3, $4, $5, $6}')
    tipo=$(echo "$linha" | awk '{print $1}')

    echo "Evento: $tipo | Data/Hora: $data"
done
