#!/usr/bin/env bash

if [ -f /var/log/auth.log ]; then
    LOG="/var/log/auth.log"
elif [ -f /var/log/secure ]; then
    LOG="/var/log/secure"
else
    echo "Arquivo de log não encontrado."
    exit 1
fi

echo "RELATÓRIO DE USO DO SUDO"
echo "Gerado em: $(date +'%d/%m/%Y')"
echo "----------------------------------------"

grep 'sudo:' "$LOG" | grep 'COMMAND=' | while read -r linha
do
    data_hora=$(echo "$linha" | awk '{print $1, $2, $3}')
    usuario=$(echo "$linha" | sed -n 's/.*sudo: \([^ ]*\) .*/\1/p')

    echo "Data/Hora: $data_hora | Usuário: $usuario"
done
