#!/usr/bin/env bash

#!/bin/bash

echo "RELATÓRIO DE ERROS E FALHAS DO KERNEL"
echo "Data do relatório: $(date +'%d/%m/%Y')"
echo "----------------------------------------"

dmesg | grep -Ei "error|fail|warn|critical|panic" | while read linha
do
    echo "$linha"
done
